### ISSUE TITLE
how change mp4 to flv with actionScript ?

### ISSUE THREAD

**Issue by keerkeerhi** [rainbowcreatures/FlashyWrappers#1]
I would like to use the data generated in the web model to achieve the MP4 stream playback, you can help me?

**Comment by rainbowcreatures** [comment]
Hey, there is an unifished way to do that, but it should more or less work. Check out "playVideo" method in 

[https://github.com/rainbowcreatures/FlashyWrappers/blob/master/AS3/com/rainbowcreatures/FWVideoEncoder.as
](https://github.com/rainbowcreatures/FlashyWrappers/blob/master/AS3/com/rainbowcreatures/FWVideoEncoder.as
)

Its the FLVByteArrayPlayer class in FLASCC branch.

For Flash, It uses that 3rd party class to swap mp4 header for flv header. The only issue I saw was with the first keyframe not being properly replayed.
