### ISSUE TITLE
Developer needed

### ISSUE THREAD

**Issue by bergmd** [rainbowcreatures/FlashyWrappers#13]
Hello, I am looking for a developer to help with this and also to get information on how to remove watermark from Android. My email is (tab at report.ly). Thanks In Advance, 
Troy

**Comment by rainbowcreatures** [comment]
Hey Troy, the watermark removal should be fairly easy on Android, it is just rendered as MovieClip in the AS3 ANE wrapper (unlike the other platforms where its embedded in the native code). It can be influenced by the compile flag DEMO. Example in source code:

```
			if (platform == 'ANDROID') {
				CONFIG::DEMO {
					_parent.addChild(lgBMP);
					_ctx.call('fw_setLogo', lgBMP.bitmapData.getPixels(new Rectangle(0, 0, lgBMP.width, lgBMP.height)));
				}
			}

```

In buildane_androidHW.bat, change -define=CONFIG::DEMO,true to false (to build a version without the logo).
