### ISSUE TITLE
ANE x86 support

### ISSUE THREAD

**Issue by mspdevelopers** [rainbowcreatures/FlashyWrappers#15]
The current sdk only has support for #-ARM.
Is it possible to add the x86 support too?

**Comment by rainbowcreatures** [comment]
Hey, yeah it should be possible, I'm not actively working on the project right now though and not sure when/if time frees up for me to resume. You are welcome to add this though.

**Comment by rainbowcreatures** [comment]
2.6 should have x86 support (though its technically still the same Java code, there is no native part). Closing issue.
