### ISSUE TITLE
FlashyWrappers on Android devices with high resolution

### ISSUE THREAD

**Issue by zoreslavs** [rainbowcreatures/FlashyWrappers#17]
Hi,

We exploring some issue with the screen blinking using FlashyWrappers on Android devices with high resolution (e.g. Samsung Galaxy 7, Motorola XT1254).

Here you can watch video taken from those devices:
https://drive.google.com/open?id=0B8R1h4LnVnSFZHRQN1diOEU2OUE
https://drive.google.com/open?id=0B8R1h4LnVnSFVnlIZDNtXy0wVFU

Can you please help us? It's an emergency.

P.S. We tried to use both GPU and direct render modes.

**Comment by bergmd** [comment]
![504197333](https://cloud.githubusercontent.com/assets/9008542/21457104/4a674ae2-c8f2-11e6-9c56-29353e826325.jpg)

Here is a photo of the issue. We should also note that we tested this on a less complex animation with only FlashWrapper contained in the build.

**Comment by zoreslavs** [comment]
Update: when we use "direct" render mode screen blinking disappears but then we have problems with Sound Mixer.

**Comment by rainbowcreatures** [comment]
Never got to this, the project ceased to be commerical as I was unable to do fulltime support for free. If somebody still has this issue let me know - I'll be willing to do paid support for urgent issues.

**Comment by rainbowcreatures** [comment]
Well I finally reproduced this on my new phone and 2.6 update seems to fix this. If not revive this thread, closing it for now.
