### ISSUE TITLE
ANE missing FWVideoEncoder?

### ISSUE THREAD

**Issue by gideonmarked** [rainbowcreatures/FlashyWrappers#2]
So I was trying to develop an app using AIR. I am using FlashyWrappers for the video recording. So I added the ANE but it seems to be looking for the FWVideoEncoder, so I added SWC or the source files but it doesn't really solve the problem. Am I missing something?

**Comment by rainbowcreatures** [comment]
You shouldn't  combine ANE / SWC. ANE is for AIR, SWC is for Flash target only. Are you able to build any examples? Which platform do you target with the ANE?

**Comment by gideonmarked** [comment]
I used ANE and I am targeting Desktop AIR. I tried using it without SWC however it returns the error. VerifyError: Error #1014: Class com.rainbowcreatures::FWVideoEncoder could not be found.

**Comment by gideonmarked** [comment]
Sorry for being a noob at this point. I've managed to make it work by enabling the Package settings for ANE.
