### ISSUE TITLE
ANE problem for android

### ISSUE THREAD

**Issue by idomadhukar** [rainbowcreatures/FlashyWrappers#22]
I trying to publish the project for android. When i try to publish i get following error:
**The content cannot be loaded because there was a problem loading an extension: Error: Requested extension com.rainbowcreatures.FWEncoderANE is not supported for Windows-x86.**

Is there any solution for this problem?
P.S. I am using animate cc

**Comment by vorlovsky** [comment]
You are definitely not publishing your project for Android, but trying to run it in Win simulator. Make sure that project settings are correct and it's really targeting Android platform (and for debug version - it should be set up to run on a real device, not simulator).

**Comment by rainbowcreatures** [comment]
Yeah "is not supported for Windows-x86" confirms what vorlovksy said.
