### ISSUE TITLE
Stage size seems to override capture size

### ISSUE THREAD

**Issue by slaymantis** [rainbowcreatures/FlashyWrappers#24]
If I set the capture width for example:
myEncoder.setDimensions(640, 360);
When its captures and saves the file it always seems to match my app stage size.
So for example my app is 1920x1080 then the video encodes are 1920x1080
If I change my stage size then the encodes always seem to match the stage size

I am using 
myEncoder.capture(vid) which is also setup for 640x360

**Comment by slaymantis** [comment]
I seem to be answering my own issues! But hopefully it helps someone else out.
Its important to start with:
myEncoder.load

The process works without it but this makes sure that all your ecoding sizes and other features get initialized.

I noticed that it wasn't making that initial call first.

**Comment by rainbowcreatures** [comment]
Hah yeah the API could surely use some more work to prevent this kinds of issues :)
