### ISSUE TITLE
some question about FW "Standard"

### ISSUE THREAD

**Issue by chengyu2333** [rainbowcreatures/FlashyWrappers#29]
FW "Standard" version doesn't include "Flash Player OGV / MP4 encoder" and "Android MP4 encoder (alpha)"?
If I buy it，Where do I download it？

**Comment by rainbowcreatures** [comment]
Hey, that's right, Android and Flash Player encoders are included only in FW "Premium", as those are usually harder for me to support.

You'll recieve a download link automatically after purchase for either version.

**Comment by qickrooms** [comment]
Hi, I tried to request the download link but it does not seem to be working right now. You had suggested if the link request fails to add an issue here.

I am interested in commercial version but hoping to start with non commercial version first. Be great if can share the link. 

My email is jasen.martin[@]gmail.com.

**Comment by rainbowcreatures** [comment]
Hey, thats strange, I just tested and the link is working just fine for me. I'll contact you via email.

**Comment by rainbowcreatures** [comment]
Oh, I just noticed this thread is from 2018, but was closed just now, hence I got the git alert. Perhaps we already talked about this long time ago. Nevermind :)
