### ISSUE TITLE
Application Sandbox

### ISSUE THREAD

**Issue by gideonmarked** [rainbowcreatures/FlashyWrappers#3]
The encoder.load() method doesn't seem to work in AIR.

**Comment by rainbowcreatures** [comment]
It won't work if you're using SWC inside an AIR app...loading the FW's helper SWF will fail(this approach is only used in the Flash target though, you shouldn't use FlashyWrappers SWC in AIR like I mentioned earlier, only ANE's).

**Comment by gideonmarked** [comment]
I used ANE and I am targeting Desktop AIR. I tried using it without SWC however it returns the error. VerifyError: Error #1014: Class com.rainbowcreatures::FWVideoEncoder could not be found.

**Comment by gideonmarked** [comment]
Sorry for being a noob at this point. I've managed to make it work by enabling the Package settings for ANE.

**Comment by rainbowcreatures** [comment]
No prob :)
