### ISSUE TITLE
Paid through paypal, on flashywrappers.com

### ISSUE THREAD

**Issue by chrischao-chn** [rainbowcreatures/FlashyWrappers#46]
Not sure about the next step, we would like to get the licensed version, and remove the logo...

**Comment by chrischao-chn** [comment]
Paid from: chris***chen@gmail.com

Would you mind check your email...

**Comment by rainbowcreatures** [comment]
I will

**Comment by rainbowcreatures** [comment]
Checked and replied, thanks!
