### ISSUE TITLE
I am having the following error...  "Calling finish but you didn't start recording."

### ISSUE THREAD

**Issue by rubel** [rainbowcreatures/FlashyWrappers#5]
I am having the following error...  "Calling finish but you didn't start recording."

Calling finish but you didn't start recording.
    at com.rainbowcreatures::FWVideoEncoder/throwError()
    at com.rainbowcreatures::FWVideoEncoder/finish()
    at com.rainbowcreatures.swf::FWVideoEncoder/finish()[C:\wamp\www\flashywrappers_svn\FW_src_stable\FlasCC\SWFBridge\com\rainbowcreatures\swf\FWVideoEncoder.as:205]
    at Helloworld/onFrame()[/Volumes/PWD/My Apps/EasySketchPro/video_render/3/FW_2_55_premium/examples/exampleHelloworld/Helloworld.as:104]
Cannot display source code at this location.

**Comment by rainbowcreatures** [comment]
Answered that one already in the earlier thread.

**Comment by rubel** [comment]
Here is the code

package  {
	
	import flash.display.MovieClip;
	import com.rainbowcreatures.*;
	import com.rainbowcreatures.swf.*;
	import flash.events.StatusEvent; // in case you're not importing this already
	import flash.events.Event; // in case you're not importing this already
	import flash.events.IOErrorEvent;
	import flash.utils.ByteArray;
	import flash.net.FileReference;
	import flash.text.TextField;
	import flash.text.TextFormat;
	import flash.events.MouseEvent;
	import flash.system.Security;

	[SWF(width=320,height=320, frameRate='24')]		
	public class Helloworld extends MovieClip {
		
		var myEncoder:FWVideoEncoder;
		var frameIndex:Number = 0;
		var maxFrames:Number = 50;
		var txt:TextField = new TextField();
		
		public function Helloworld() {
			// constructor code
			//Security.allowDomain("*");
			//Security.loadPolicyFile("http://hamzagames.com/crossdomain.xml");
			var tf:TextFormat = new TextFormat("Arial", 30, 0XAA5050);
			txt.text = "Hello world!";			
			txt.setTextFormat(tf);
			txt.width = 200;
			txt.y = 180;
			addChild(txt);			
			myEncoder = FWVideoEncoder.getInstance(this);	
			myEncoder.addEventListener(StatusEvent.STATUS, onStatus);
			myEncoder.load("http://hamzagames.com/easy_sketch_pro/lib/FlashPlayer/mp4/");
			//myEncoder.load("../../lib/FlashPlayer/mp4/");
			
			stage.addEventListener(MouseEvent.CLICK,clicked);
		}
		function clicked(e:MouseEvent):void{
			var bo:ByteArray = myEncoder.getVideo();
				trace("Recording finished, video length: " + bo.length);								
				
				// save the file for check
				var saveFile:FileReference = new FileReference();
				saveFile.addEventListener(Event.COMPLETE, saveCompleteHandler);
				saveFile.addEventListener(IOErrorEvent.IO_ERROR, saveIOErrorHandler);
				saveFile.save(bo, "video.mp4");								
			
			/*trace('here i am .... clicked.............');
			myEncoder.start(24);
			trace("FlashyWrappers ready! Init...");
			addEventListener(Event.ENTER_FRAME, onFrame);*/
		}
		
		private function onStatus(e:StatusEvent):void {
			trace("Got status");
			if (e.code == "ready") {
				trace('////////////////////////////////////////////////////////');
				myEncoder.setDimensions(stage.stageWidth, stage.stageHeight);
				myEncoder.start(24);
				trace("FlashyWrappers ready! Init...");
				addEventListener(Event.ENTER_FRAME, onFrame);
			}else if (e.code == "encoded") {
				var bo:ByteArray = myEncoder.getVideo();
				trace("Recording finished, video length: " + bo.length);								
				
				// save the file for check
				var saveFile:FileReference = new FileReference();
				saveFile.addEventListener(Event.COMPLETE, saveCompleteHandler);
				saveFile.addEventListener(IOErrorEvent.IO_ERROR, saveIOErrorHandler);
				saveFile.save(bo, "video.mp4");								
			}
			else{
				trace(e.code+'//////////////////////'+e);
			}
		}
		
		private function onFrame(e:Event):void {
			// animate the rectangle
			txt.x++;

			// clear the background, otherwise all transparency will be black by default in the video
			graphics.beginFill(0XFFFFFF, 1);
			graphics.drawRect(0, 0, stage.stageWidth, stage.stageHeight);
			graphics.endFill();
			
			// render one frame of your stuff into someMovieClip, then capture and
			// add one frame into the FlashyWrappers video encoder like this:
			myEncoder.capture(this);
			frameIndex++;
			if (frameIndex >= maxFrames - 1) {
				removeEventListener(Event.ENTER_FRAME, onFrame);				
				myEncoder.finish();
				/*var bo:ByteArray = myEncoder.getVideo();
				trace("Recording finished, video length: " + bo.length);								
				
				// save the file for check
				var saveFile:FileReference = new FileReference();
				saveFile.addEventListener(Event.COMPLETE, saveCompleteHandler);
				saveFile.addEventListener(IOErrorEvent.IO_ERROR, saveIOErrorHandler);
				saveFile.save(bo, "video.mp4");	*/							
			}
		}							

		// file was saved
		private function saveCompleteHandler(e:Event):void {
			trace("Video saved!");
		}
		
		// some error happened
		private function saveIOErrorHandler(e:IOErrorEvent):void {
			trace("Video NOT saved:(");
		}

	}	
}

**Comment by rubel** [comment]
??

**Comment by vorlovsky** [comment]
Got the same issue for iOS.

**Comment by vorlovsky** [comment]
@rubel I did the same mistake as you - you let myEncoder.finish() to be called several times while frameIndex > (maxFrames - 1).
