### ISSUE TITLE
macOS : Error #2123: Security sandbox violation

### ISSUE THREAD

**Issue by goodintention** [rainbowcreatures/FlashyWrappers#50]
Hello,
I get security error when calling capture() on macOS?
SecurityError: Error #2123: Security sandbox violation: BitmapData.draw: app:/com.rainbowcreatures.FWEncoderANE cannot access null. No policy files granted access.
at flash.display::BitmapData/draw()
at com.rainbowcreatures::FWVideoEncoder/capture()[/Users/vmmac/Documents/FlashyWrappers/AS3/com/rainbowcreatures/FWVideoEncoder.as:2199]

**Comment by goodintention** [comment]
This security error occur when capturing StageVideo.

**Comment by rainbowcreatures** [comment]
This has nothing to do with FW, its policy issue, trying to capture a Bitmap from a different domain probably (another remote possibility might be trying to use the Flash SWC where you should use the ANE, those don't mix well). 

Anyway I believe we discussed exactly this issue over e-mail already, so I'll close this.

**Comment by rainbowcreatures** [comment]
Closing
