### ISSUE TITLE
Error: [FlashyWrappers error] FW_SWFBridge_ffmpeg.swf couldn't be loaded! Please make sure it's in the same path as your main SWF or specify the path in the 'load' method like this: myEncoder.load('path/to/FW_SWFBridge_ffmpeg/')

### ISSUE THREAD

**Issue by Mohib1992** [rainbowcreatures/FlashyWrappers#6]
When i'm open helloworld.fla and start compiling this error happening.I check the dir FW_SWFBridge_ffmpeg.swf was there.

**Comment by rainbowcreatures** [comment]
What is your target platform, do you compile for Flash web player? (its only there where this file is needed).

Also, where exactly lives the file. Check again the path, and paste here where the 'load' points to(for example):

`myEncoder.load("../../lib/FlashPlayer/mp4/");			`

To make sure, try to copy the SWFBridge file into the same folder like the example fla and just use:

`myEncoder.load();`

It should work in case it was an issue with path...

**Comment by mrgoonie** [comment]
I got stuck at this point:

```
Got status
[FlashyWrappers] It is recommended your video dimensions are multiplies of 16. On some platforms, like iOS, other dimensions might cause issues.
[FlashyWrappers] Figuring out microphone permissions
[FlashyWrappers] Returned true
[FlashyWrappers] Calling init
Got status
[FlashyWrappers] Initializing...
TypeError: Error #1009: Cannot access a property or method of a null object reference.
	at global/com.fw_flascc::F_thr_new()
	at global/com.fw_flascc::F__pthread_create()
	at global/com.fw_flascc::F__ZN16FW_ffmpeg_encode11ffmpeg_initEPhS0_S0_iiiiiiiiiimii()
	at global/com.fw_ffmpeg::ffmpeg_init()
	at Function/FWVideoEncoder.as$1:anonymous()
	at com.rainbowcreatures::FWVideoEncoder/askMicPermission()
	at com.rainbowcreatures::FWVideoEncoder/start()
	at com.rainbowcreatures.swf::FWVideoEncoder/start()
	at airwrite_flashy_fla::MainTimeline/onStatus()
	at flash.events::EventDispatcher/dispatchEventFunction()
	at flash.events::EventDispatcher/dispatchEvent()
	at com.rainbowcreatures.swf::FWVideoEncoder/onEncoderLoaded()
```

**Comment by rainbowcreatures** [comment]
I have a feeling I saw this happening in the latest version. Are you using OGV or MP4 as target?

**Comment by mrgoonie** [comment]
I tried both OGV and MP4, same result.

**Comment by rainbowcreatures** [comment]
Ok, I'd need a code to reproduce this. Did you try exampleCamera or something on your own?

I strongly suspect it has to do with changes in FW2.6, as a workaround you might also try this older version of FW - most of the changes I've made did not affect the Flash version anyway (except for breaking it as it seems):

http://flashywrappers.com/download/FW_2_55_free.zip
